### PR TITLE
Add minimum drop height

### PR DESCRIPTION
**Pull request by Vap0r1ze**
This will prevent the backpack from dropping below Y=1

### CODE REVIEW

**Comment by Highdefkitten** [comment]
Much needed feature.

**Comment by Tiviacz1337** [comment]
But why? Like if you want to not drop backpack somehow, just change keepInventory to true, else backpack will drop like normal item

**Comment by Vap0r1ze** [comment]
This is for compatibility with mods that generate structures around your death (eg: GraveStone).

**Comment by Tiviacz1337** [comment]
Okay, I'll probably add this

**Comment by Vap0r1ze** [comment]
Is this being added?

**Pull request closed without merging**
