### PR TITLE
Added back capability to milk cows with hose.

### PR DESCRIPTION
**Pull request by Darkona**
Fixed use of deprecated methods from forge.
You can now milk cows directly with the hose.
Enabled forge milk fluid as default for this to work.
Moved a bit of code around in ItemHose for filling tanks to avoid duplications.

### CODE REVIEW

**Comment by Tiviacz1337** [comment]
What about Fabric though?

**Comment by Darkona** [comment]
Sorry, I don't know anything about Fabric :( but even if the fix is only for forge it should work. I'm leveraging Forge's milk fluid for this to avoid adding the fluid in the mod itself. I have no idea how Fabric works or whether it can do the same thing.

**Comment by Tiviacz1337** [comment]
I mean the problem is I want to keep Fabric/Forge version as close as possible and milk fluid is not available on Fabric. I'll consider adding this on Forge though

**Comment by Darkona** [comment]
I think its super valid that both versions be capable of different things, it is just the perk of using one mod loader or the other, they offer different capabilities and features. The next best solution is adding milk fluid in Fabric for this to work if possible.

**Comment by Tiviacz1337** [comment]
I'll probably add milk on fabric but not as placeable fluid.

**Comment by Tiviacz1337** [comment]
I'll probably merge this pr and implement milk on fabric for the next update

**Pull request merged**
