### PR TITLE
Update `ru_ru.json`

### PR DESCRIPTION
**Pull request by mpustovoi**
Parity with with `en_us.json`.

### CODE REVIEW

**Comment by Tiviacz1337** [comment]
https://localazy.com/p/travelers-backpack
check here, this is the latest translation

**Comment by mpustovoi** [comment]
The latest versions of the mod for Forge 1.20.1 and NeoForge 1.21.1 contain 282 source language keys each. The Fabric 1.20.1 version has 298 keys, and Fabric 1.21.1 has 293. In each case, it's almost twice as much as it's now on [Localazy](https://localazy.com/p/travelers-backpack), where at the moment there are only 163 source keys.
Mainly there are no source keys for configs (both for (Neo)Forge and Fabric), and many keys are generally outdated.

Please update the localization page of your mod.

**Comment by Tiviacz1337** [comment]
I havent updated the localazy yet with new translations, I want to finish releasing the ability changes and proper changes for localazy will be made to include all latest source keys and translations

**Comment by mpustovoi** [comment]
Oh, I see that there have been no language updates for about 10 months...
Well, I wish you every success. 🙏🏻

**Comment by Tiviacz1337** [comment]
And that should happen by the end of this weekend 👌

**Pull request closed without merging**
