### PR TITLE
Updating it localisation

### PR DESCRIPTION
**Pull request by BlackShadow77**
pull request to update italian localisation.
It's still a work in progress but i'm also waiting for the issue #510 to end

### CODE REVIEW

**Comment by BlackShadow77** [comment]
Finished to translate the file. I'll wait updates on issue #510 to mark that as ready

**Comment by Tiviacz1337** [comment]
https://localazy.com/p/travelers-backpack
If you could edit lang file here, I'd be glad :) 
There is latest lang file which will be used in latest update

**Comment by BlackShadow77** [comment]
Hi @Tiviacz1337, ty for the reply.

I tried the website and i need to do a lot of work "manually" to re-do translations on this (new) system; i'll take some time to update all.

Anyway i still need more context about #510, tell me how this work so i know how to proper translate entries

**Comment by BlackShadow77** [comment]
Hi @Tiviacz1337 i still can't work on it properly right now but i'll tell u meanwhile what entries need more context as wrote in #510:

-screen.travelersbackpack.none
-ability.travelersbackpack.item_and_block(in particular the §6 §e symbols)
-ability.travelersbackpack.item
-ability.travelersbackpack.block
-screen.travelersbackpack.settings_back

**Pull request closed without merging**
